# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gabriël Shamon
title: Student Computer Science
email: gabrielshamon1@hotmail.nl
website: www.google.nl

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: gabriel
github_username:  gp2001
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: gabriel.shamon
# flickr_username: jekyll
instagram_username: gabrielpoleza_
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ik.jpg
about_content: | # this will include new lines to allow paragraphs
  Hallo, mijn naam is Gabriël en ik ben een universitair Informatica student. Ik ben momenteel freelancer bij youngones en heb meerdere ervaringen opgedaan met verschillende soorten banen. Ik heb enige ervaringen opgedaan tijdens mijn studie met software en web apps.

  Mijn meeste ervaringen zijn in: <mark>C#</mark>, maar kan ook <mark>Python</mark>, <mark>Haskell</mark>, <mark>Javascript</mark>, <mark>Css</mark>, <mark>Html</mark> en <mark>sql</mark>.

  Ook spreek ik <mark>Nederlands</mark>, <mark>Engels</mark>, <mark>Chaldeeuws</mark>, en <mark>Duits</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DisneyRoute
        link: https://www.instagram.com/disneyroute/
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Hier heb ik mijn eerste ervaringen opgedaan met het werken in teamverband, snelste route-algoritme, databases en meer.
        description: | # this will include new lines to allow paragraphs
          Dit project was om meer te leren met <mark>C#</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Albert Heijn
        link: www.ah.nl
        # link_text: boringcompany.com
        sub_title: Teamleider
        caption: Januari 2017 - Maart 2017
        quote: >
          Het opdoen van Leidinggevende en sociale ervaringen.
        description: | # this will include new lines to allow paragraphs
            Ieder bedrijf heeft iemand nodig die orde houdt en eventueel instructies geeft om het bedrijf draaiende te houden. Dit kent uitdagingen om zo optimaal mogelijk, medewerkers positief bezig te houden.
            Hier heb ik mijn  <mark>Bedrijfs Hulp Verlening Diploma</mark> behaald.
      - layout: left
        title: Groot en Klein
        # link:
        # link_text: boringcompany.com
        sub_title: Verhuizer
        caption: Juli 2019 - september 2019
        quote: >
          Het opdoen van zwaarwerk ervaringen.
        description: | # this will include new lines to allow paragraphs
            Een bedrijf heeft ook werkers nodig. Dit kan soms zwaar zijn. Deze ervaring helpt om dit in te zien en doorgeefvermogen te ontwikkelen.
      - layout: left
        title: Picnic, Dani's Corner en Parakalo
        link: https://picnic.app
        # link_text: boringcompany.com
        sub_title: bezorger
        caption: Januari 2020 - September 2020
        quote: >
          Het opdoen van rij-ervaringen.
        description: | # this will include new lines to allow paragraphs
           Na het behalen heb ik hier mijn rijervaringen opgedaan.
      - layout: left
        title: Covebo
        link: www.covebo.nl
        # link_text: boringcompany.com
        sub_title: Algemeen medewerker
        caption: Juni 2020 - Augustus 2020
        quote: >
         Zwaar vakantiebaantje
        description: | # this will include new lines to allow paragraphs
            Een bedrijf heeft ook werkers nodig. Dit kan soms zwaar zijn. Deze ervaring helpt om dit in te zien en doorgeefvermogen te ontwikkelen.
      - layout: left
        title: Unagi Sushi
        link: www.unagisushi.nl
        # link_text: boringcompany.com
        sub_title: Allround medewerker
        caption: September 2020 - Heden
        quote: >
          Studiekosten bijverdiensten
        description: | # this will include new lines to allow paragraphs
            Hier doe ik kassa, stuur ik bezorgers aan, pak ik bestellingen in, help ik in de keuk en bezorg ik.
      - layout: left
        title: youngones
        link: www.youngones.com
        # link_text: boringcompany.com
        sub_title: Freelancer
        caption: Juni 2020 - Heden
        quote: >
          Het opdoen van ervaringen bij meerdere soorten banen.
        description: | # this will include new lines to allow paragraphs
            Een freelancer kent veel verantwoordelijkheden, dit doe ik voor bijverdiensten en de bijbehorende ervaringen.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universiteit Utrecht
        caption: 2020 - nu
        sub_title: BSc Computer Science
        quote: >
          In Utrecht kijken studenten over de grenzen van hun vakgebied heen. Studenten en toponderzoekers werken in hechte communities samen aan een betere toekomst.
        description: | # this will include new lines to allow paragraphs
          Ik ben momenteel bezig met wetenschappijl onderwijs. Hier heb ik geleerd dat mijn manier van denken, professioneler veranderd is. Het speciaal zijn en bijdragen aan denkkracht zorgt op het vooruitgaan in de toekomst.
      - layout: left
        title: Voortgezet Wetenschappelijk Onderwijs/ Atheneum
        caption: september 2014 - Juli 2020
        sub_title: NT/NG met economie
        quote: >
          Op school doe je kennis en vaardigheden op waarmee je naar zelfstandigheid groeit. Onze school is een veilige omgeving waarin mensen je kennen. Een omgeving ook die ruimte biedt om te groeien naar volwassenheid. Vallen en opstaan hoort daarbij, net als de wereld verkennen.
          Goed onderwijs is het eerste wat je van een school mag verwachten. Leren gebeurt op het Cals College in de vaklessen en daarbuiten. Leerlingen hebben eigen kwaliteiten en interesses. Deze kunnen ze via het brede aanbod van activiteiten verder ontwikkelen.
        description: | # this will include new lines to allow paragraphs
          Tijdens mijn studie in de middelbareschool ben ik veel uitdaging aangegaan. Ik heb de zwaarste vakkenpaketten genomen en ben dus afgestudeerd met twee diploma's. Naast deze diploma's heb ik ook een Goethe zertifikat behaald.
          In mijn derde jaar heb ik een eindrapport gekregen met een gemiddelde van een 8,8, hierna mocht ik al deelnemen aan projecten met samenwerking met Universiteit Utrecht.


  - title: Wat meer over mij
    layout: text
    content: | # this will include new lines to allow paragraphs
      Naast mijn studie en werkervaringen vind ik het volgende ook leuk:
      - Mensen leren kennen
      - Voetbal
      - Hulp aanbieden
      - Wat nieuws leren
      - Sporten
      - Gamen 
      - [Een ninja worden](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/cutie.jpg "Cute")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
