# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
github: [metadata]

# Content configuration version
version: 2

# Personal info
name: Gabriël Shamon
title: Software Engineer at ICT Group, MSc Applied Data Science, BSc Computer Science
email: gabrielshamon1@hotmail.nl
website: https://gp2001.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: gabriel
github_username:  gp2001
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: gabriel.shamon
# flickr_username: jekyll
instagram_username: gabrielpoleza_
linkedin_username: gabriël-shamon-7839a576
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: PDF
    icon: fas fa-save
    url: /assets/resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

#About Section
about_title: Over mij
about_profile_image: images/ik.jpg
about_content: | # this will include new lines to allow paragraphs
  Hallo, mijn naam is Gabriël en ik ben een universitair informaticastudent. Ik ben momenteel freelancer bij YoungOnes en heb meerdere ervaringen opgedaan met verschillende soorten banen. Ik heb tijdens mijn studie enige ervaring opgedaan met software en web-apps.

  Mijn meeste ervaring is in <mark>C#</mark>, maar ik kan ook <mark>Python</mark>, <mark>Haskell</mark>, <mark>JavaScript</mark>, <mark>CSS</mark>, <mark>HTML</mark>, <mark>SQL</mark> en <mark>R</mark>. Momenteel ben ik bezig met trainingen voor <mark>AI</mark>, <mark>Intro voor Embedded Software</mark>, <mark>Azure Fundamentals</mark> en <mark>Power BI</mark>.

  Ik spreek ook <mark>Nederlands</mark>, <mark>Engels</mark>, <mark>Chaldeeuws</mark> en <mark>Duits</mark>.

content:
  - title: Projecten # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Generating Structured Synthetic Data; Empowering Stater's Mortgage Services with a Large Language Model
        # link: https://www.youtube.com/watch?v=vV1JjrZjnxk
        # link_text: Project Video
        quote: >
          In dit project heb ik ruwe data om weten te zetten door middel van LLMs naar een ORPO Dataset voor het genereren van een fine-tuned LLM
        description: | # this will include new lines to allow paragraphs
          Ik heb recent ervaring opgedaan met het omzetten van ruwe website scraped data naar een ORPO (Odd Ratio Preference Optimization) dataset met behulp van <mark>Large Language Models (LLMs)</mark> en <mark>prompt engineering</mark>. Ik heb geleerd hoe ik LLMs kan trainen en fine-tunen om specifieke taken uit te voeren, zoals het omzetten van ongestructureerde data naar een gestructureerd formaat.

          In dit project heb ik vooral gewerkt aan het ontwikkelen van prompts en het trainen van LLMs om de data om te zetten. Ik heb ook ervaring opgedaan met het optimaliseren van de prestaties van de LLMs en het verbeteren van de nauwkeurigheid van de resultaten.

          Een belangrijk onderdeel van het project was de validatie van de gegenereerde data. Ik heb hiervoor gebruik gemaakt van verschillende checks, zoals de halucination score en token similariteitsanalyses. Deze checks hebben mij geholpen om de kwaliteit van de gegenereerde data te beoordelen en te verbeteren.

          Door dit project heb ik een dieper inzicht gekregen in de mogelijkheden en beperkingen van LLMs en prompt engineering, en heb ik geleerd hoe ik deze technologieën kan inzetten om complexe data-omzettingstaken uit te voeren. Ook heb ik ervaring opgedaan met het <mark>valideren</mark> van gegenereerde data en het gebruik van verschillende checks om de kwaliteit te beoordelen. Ik ben trots op wat ik heb bereikt en kijk uit naar toekomstige projecten waarin ik deze vaardigheden kan toepassen."
      - layout: top-middle
        title: Verdachte Tijdlijn
        link: https://www.youtube.com/watch?v=vV1JjrZjnxk
        link_text: Project Video
        quote: >
          In dit project heb ik in een groep van 10 studenten een programma gerealiseerd voor de Nationale Poltie en Koninklijke Marechaussee.
        description: | # this will include new lines to allow paragraphs
          Ik heb hier meer ervaring opgedaan met <mark>Scrum</mark>, <mark>Agile Werken</mark>, <mark>Retro's</mark>, <mark>Docker</mark>, <mark>Python</mark> en <mark>GitHub</mark>.
          We moesten camerabeelden omzetten in zinnen, zodat er legaal naar objecten gezocht zou kunnen worden. Aan dit project heb ik vooral gewerkt aan de <mark>Back-End</mark>.
          Ik heb geleerd om <mark>objectdetectie</mark> en <mark>tracking</mark> toe te passen. Ook heb ik een model zelf getraind voor <mark>kledingdetectie</mark> en heb ik een <mark>kleurendetectie</mark> zelf geschreven.
          We waren een half jaar bezig om dit fantastische project te realiseren, klik op de link om de video te bekijken.
      - layout: top-middle
        title: Automatisch Factureren
        link: gp2001.github.io/facturen
        link_text: Website
#        additional_links:
#          - title: gp2001/IntroductieProject
#            icon: fab fa-github
#            url: https://github.com/gp2001/IntroductieProject
        quote: >
          Deze website maakt het makkelijker om facturen te genereren.
        description: | # this will include new lines to allow paragraphs
          Ik heb hier mijn <mark>JavaScript</mark> vaardigheden vooral verbeterd.
      - layout: top-middle
        title: Websites voor Diverse Klanten
        link: https://www.polezait.nl
        quote: >
          Ik heb meerdere websites ontwikkeld voor verschillende bedrijven en professionals onder mijn bedrijfje Polezait.nl.
        description: | # this will include new lines to allow paragraphs
          Als eigenaar en webontwikkelaar van Polezait.nl heb ik een reeks op maat gemaakte websites gecreëerd om tegemoet te komen aan de unieke behoeften van diverse klanten. Mijn werk omvatte het ontwikkelen van websites voor restaurants, kappers, makelaars, zonnepanelenbedrijven en zzp'ers die behoefte hebben aan geautomatiseerde facturatie-oplossingen. Bij elk project heb ik mijn vaardigheden in <mark>HTML</mark>, <mark>CSS</mark> en <mark>JavaScript</mark> toegepast en verbeterd om moderne en functionele websites te leveren die de identiteit en doelen van mijn klanten weerspiegelen. Deze ervaring heeft mijn vermogen versterkt om effectief te communiceren met klanten, hun visie te begrijpen en te vertalen naar tastbare digitale oplossingen.
      - layout: top-middle
        title: DisneyRoute
        link: https://www.instagram.com/disneyroute/
        # link_text: Project Website
        additional_links:
          - title:  gp2001/IntroductieProject
            icon: fab fa-github
            url: https://github.com/gp2001/IntroductieProject
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Hier heb ik mijn eerste ervaringen opgedaan met het werken in teamverband, snelste route-algoritme, databases en meer.
        description: | # this will include new lines to allow paragraphs
          Dit project was om meer te leren met <mark>C#</mark>.

  - title: Werk Ervaringen # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Albert Heijn
        link: www.ah.nl
        link_text: Albert Heijn
        sub_title: Teamleider
        caption: Januari 2017 - Maart 2019
        quote: >
          Het opdoen van Leidinggevende en sociale ervaringen.
        description: | # this will include new lines to allow paragraphs
            Ieder bedrijf heeft iemand nodig die orde houdt en eventueel instructies geeft om het bedrijf draaiende te houden. Dit brengt uitdagingen met zich mee om de medewerkers zo optimaal mogelijk en positief bezig te houden. Hier heb ik mijn <mark>Bedrijfshulpverlening diploma</mark> behaald.
      - layout: left
        title: Groot en Klein
        # link:
        # link_text: boringcompany.com
        sub_title: Verhuizer
        caption: Juli 2019 - september 2019
        quote: >
          Het opdoen van zwaarwerk ervaringen.
        description: | # this will include new lines to allow paragraphs
            Een bedrijf heeft medewerkers nodig die in staat zijn om zwaar werk te verrichten. Deze ervaring helpt hen om in te zien hoe dit moet gebeuren en om doorgeefvermogen te ontwikkelen.
      - layout: left
        title: Picnic, Dani's Corner en Parakalo
        link: https://picnic.app
        link_text: Picnic
        sub_title: bezorger
        caption: Januari 2020 - September 2020
        quote: >
          Het opdoen van rij-ervaringen.
        description: | # this will include new lines to allow paragraphs
           Na het behalen van mijn rijbewijs, heb ik hier mijn rijervaring verbeterd.
      - layout: left
        title: Covebo
        link: www.covebo.nl
        link_text: Covebo
        sub_title: Algemeen medewerker
        caption: Juni 2020 - Augustus 2020
        quote: >
         Zwaar vakantiebaantje
        description: | # this will include new lines to allow paragraphs
            Een bedrijf heeft medewerkers nodig die in staat zijn om zwaar werk te verrichten. Deze ervaring helpt hen om in te zien hoe dit moet gebeuren en om doorgeefvermogen te ontwikkelen.
      - layout: left
        title: Unagi Sushi
        link: www.unagisushi.nl
        link_text: Unagi Sushi
        sub_title: Floormanager
        caption: September 2020 - 2023
        quote: >
          Studiekosten bijverdiensten
        description: | # this will include new lines to allow paragraphs
            Hier doe ik kassawerkzaamheden, stuur ik bezorgers aan, pak ik bestellingen in, help ik in de keuken en bezorg ik.
      - layout: left
        title: Youngones
        link: www.youngones.com
        # link_text: boringcompany.com
        sub_title: Freelancer
        caption: Juni 2020 - Heden
        quote: >
          Het opdoen van ervaringen bij meerdere soorten banen.
        description: | # this will include new lines to allow paragraphs
            Een freelancer kent veel verantwoordelijkheden, dit doe ik voor bijverdiensten en de bijbehorende ervaringen.
      - layout: left
        title: Polezait.nl
        link: www.polezait.nl
        sub_title: Eigenaar & Webontwikkelaar
        caption: Januari 2022 - Heden
        quote: >
           Ontwerpen en ontwikkelen van op maat gemaakte websites voor diverse bedrijven en professionals.
        description: | # this will include new lines to allow paragraphs
           Als eigenaar en webontwikkelaar van Polezait.nl heb ik me beziggehouden met het creëren van aantrekkelijke en functionele websites voor verschillende soorten bedrijven. Mijn werk omvatte onder andere het ontwikkelen van websites voor restaurants, kappers, makelaars, zonnepanelenbedrijven en zzp'ers die behoefte hebben aan geautomatiseerde facturatie-oplossingen. Ik heb mijn vaardigheden in HTML, CSS en JavaScript toegepast en verbeterd om aan de specifieke behoeften van elke klant te voldoen, terwijl ik tegelijkertijd mijn vermogen om effectief te communiceren met klanten en hun visie om te zetten in tastbare digitale oplossingen heb versterkt. Dit werk heeft mij waardevolle ervaring opgeleverd in zowel technische als zakelijke aspecten van webontwikkeling, waardoor ik mijzelf blijf ontwikkelen als een competente en veelzijdige webontwikkelaar.
      - layout: left
        title: ICT Group
        link: www.ict.eu
        sub_title: Software Engineer
        caption: September 2024 - Heden
        quote: >
           Ontwikkelen van innovatieve softwareoplossingen voor diverse bedrijven en organisaties.
        description: |
            Als software engineer bij ICT Group ben ik betrokken bij het ontwikkelen van complexe softwareoplossingen voor verschillende soorten bedrijven en organisaties. Mijn werk omvat het ontwikkelen van softwareoplossingen voor diverse domeinen, waaronder healthcare, automotive, traffic, hightech en energie. Ik heb mijn vaardigheden in programmeertalen zoals python en C# toegepast en verbeterd om aan de specifieke behoeften van elke klant te voldoen, terwijl ik tegelijkertijd mijn kennis aan het uitbreiden ben door trainingen in Rust, intro to Embedded software, Agile Scrum Foundation, Azure, Power BI. Dit werk heeft mij waardevolle ervaring opgeleverd in zowel technische als zakelijke aspecten van softwareontwikkeling, waardoor ik mijzelf blijf ontwikkelen als een competente en veelzijdige software engineer.
      - layout: left
        title: Vrijwilligerswerk
        # link: www.ah.nl
        # link_text: Albert Heijn
        sub_title: Het Geinsche Hof, Stichting Al Fadi en Buurtstichting.
        caption: 40+ uren
        quote: >
          Positieve onbetaalde inbreng in de maatschappij.
        description: | # this will include new lines to allow paragraphs
            Ouderen ondersteunen, de buurt vooruit helpen en gemeenschappen zich meer thuis laten voelen in een nieuwe leefsituatie. Inzet voor een goed doel vind ik belangerijk, omdat de mens ook een goede kant moet laten zien.
            

  - title: Educatie # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universiteit Utrecht
        caption: 2023 - 2024
        sub_title: MSc Applied Data Science
        quote: >
          In Utrecht kijken studenten over de grenzen van hun vakgebied heen. Studenten en toponderzoekers werken in hechte communities samen aan een betere toekomst.
        description: | # this will include new lines to allow paragraphs
         Tijdens mijn WO-master Applied Data Science ga ik geavanceerde kennis en vaardigheden opdoen in data-analyse, machine learning en statistische modellering, waardoor ik in staat zal zijn om complexe datasets te analyseren, waardevolle inzichten te verkrijgen en voorspellende modellen te ontwikkelen voor datagedreven besluitvorming.
      - layout: left
        title: Universiteit Utrecht
        caption: 2020 - 2023
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          Tijdens mijn WO-bachelor informatica heb ik een diepgaand begrip ontwikkeld van programmeerconcepten, algoritmen, gegevensstructuren en systeemanalyse, waardoor ik in staat ben complexe softwareoplossingen te ontwerpen en implementeren.
      - layout: left
        title: Voortgezet Wetenschappelijk Onderwijs/ Atheneum
        caption: september 2014 - Juli 2020
        sub_title: NT/NG met economie
        quote: >
          Op school doe je kennis en vaardigheden op waarmee je naar zelfstandigheid groeit. Onze school is een veilige omgeving waarin mensen je kennen. Een omgeving ook die ruimte biedt om te groeien naar volwassenheid. Vallen en opstaan hoort daarbij, net als de wereld verkennen.
          Goed onderwijs is het eerste wat je van een school mag verwachten. Leren gebeurt op het Cals College in de vaklessen en daarbuiten. Leerlingen hebben eigen kwaliteiten en interesses. Deze kunnen ze via het brede aanbod van activiteiten verder ontwikkelen.
        description: | # this will include new lines to allow paragraphs
          Tijdens mijn middelbare schooltijd ben ik vele uitdagingen aangegaan. Ik heb de zwaarste vakkenpakketten gekozen en ben daarom afgestudeerd met twee diploma's. Naast deze diploma's heb ik ook een Goethe-Zertifikat behaald. In mijn derde jaar ontving ik een eindrapport met een gemiddelde van 8,8. Hierdoor kreeg ik de mogelijkheid om deel te nemen aan projecten in samenwerking met de Universiteit Utrecht.

  - title: Certificaten
    layout: list
    content:
      - layout: left
        title: Microsoft Certified Azure Data Fundamentals
        link: assets/Credentials - GabrielShamon-9265 _ Microsoft Learn.pdf
        link_text: Certificate
        caption: 2024~
        quote: >
          Deze certificering toont aan dat ik kennis heb van de basisprincipes van Azure Data Services en hoe deze kunnen worden gebruikt om gegevens te beheren en te analyseren.
        description: | # this will include new lines to allow paragraphs
          In deze training heb ik kennis gemaakt met de basisprincipes van Azure Data Services en geleerd hoe ik gegevens kan beheren en analyseren met behulp van Azure. Ik heb ervaring opgedaan met het werken met Azure Data Services, het opzetten van gegevensopslag en het uitvoeren van gegevensanalyse in Azure. Deze certificering heeft mijn kennis en vaardigheden in Azure versterkt en mij in staat gesteld om effectief te werken met Azure Data Services.
      - layout: left
        title: Explore rust
        link: \assets\Certificate of Training - Gabriel Shamon.pdf
        link_text: Certificate
        caption: 2024~
        quote: >
          Rust is een systeemtaal die is ontworpen om veilige en efficiënte software te maken.
        description: | # this will include new lines to allow paragraphs
          In deze training heb ik kennis gemaakt met de basisprincipes van Rust en geleerd hoe ik veilige en efficiënte software kan ontwikkelen met deze taal. Ik heb ervaring opgedaan met het schrijven van code in Rust, het compileren van programma's en het gebruik van de Rust-toolchain. Deze training heeft mijn kennis en vaardigheden in Rust versterkt en mij in staat gesteld om complexe softwareoplossingen te ontwikkelen met deze taal.

  - title: Interesses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Voetbal: ik speel regelmatig in mijn vrije tijd en vind het leuk om naar wedstrijden te kijken.
      - Fitnessen: ik hecht veel waarde aan een gezonde levensstijl en breng daarom graag tijd door in de sportschool.
      - Gamen: ik vind het leuk om af en toe te ontspannen met een videogame.
      - Persoonlijke ontwikkeling: ik ben altijd op zoek naar manieren om mezelf te verbeteren en nieuwe vaardigheden te leren.
      - Netwerken: ik vind het leuk om nieuwe mensen te ontmoeten en te leren van hun ervaringen.
      - Op avontuur gaan: ik houd ervan om nieuwe plaatsen te ontdekken en nieuwe ervaringen op te doen, zowel in mijn eigen omgeving als daarbuiten. Ik ben altijd bereid om uit mijn comfortzone te stappen en nieuwe uitdagingen aan te gaan.

#      - [Op avontuur](https://youtu.be/SKnGqmVR8lI)

#      Look at this cool image  
#      ![Trees](/images/air.jpg "Cute")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-pdf

